### PR TITLE
Changed let to const in the setProgress method

### PR DESCRIPTION
**Pull request by raisiqueira**
Signed-off-by: Raí Siqueira <rai93siqueira@gmail.com>

### CODE REVIEW

**Comment by robertoachar** [comment]
Well done, buddy!

**Comment by zaguiini** [comment]
To be honest, that's a pretty useless change. You could completely omit this variable as well because the method called is already self-descriptive and you're really using the value that the method returns once, so there is no need to assign it a variable...

A better refactor would be changing this component from class to hooks or, even better, create a hooked version of this lib that doesn't clutter the actual div it's inserted.

**Comment by diogomoretti** [comment]
@raisiqueira thanks for your PR =]

@zaguiini I agree with you. This PR will fix the current version. The version using hooks will be changed to major ;)

**Comment by zaguiini** [comment]
> @zaguiini I agree with you. This PR will fix the current version. The version using hooks will be changed to major ;)

I don't think it's eligible to a major bump because you're not really breaking any changes, just implementing new ones -- stills backward compatible. The minor is correct as described in my PR #6.

As per: https://www.sitepoint.com/semantic-versioning-why-you-should-using/

"If you are implementing new features in a backward-compatible way, then you will bump y because this is what's called a minor version. On the other hand, if you implement new stuff that is likely to break the existing API, you need to bump x because it is a major version"

**Pull request merged**
